[platformio]
default_envs = native

[env:cortex_m4]
build_src_filter = +<*> +<deps/pqm4/pqcrystals/kyber/ref/*.c> +<deps/pqm4/common/*.c>
platform = ststm32
lib_deps = 
    https://github.com/mupq/pqm4#main
    https://github.com/intel/tinycrypt#main
board = nucleo_f446re
framework = stm32cube
build_type = release
build_flags = 
    -std=c99
    -Os
    -ffunction-sections
    -fdata-sections
    -fno-builtin-malloc
    -fno-builtin-calloc
    -fno-builtin-realloc
    -fno-builtin-free
    -fno-exceptions
    -DSTM32F446xx
    -DARM_MATH_CM4
    -D__FPU_PRESENT=1
    -DARM_MATH_MATRIX_CHECK=0
    -DARM_MATH_ROUNDING=0
    -Iinclude
    -Isrc
    -Isrc/core_rtos
    -Isrc/pqc_engine
    -Isrc/federated
    -Isrc/network
    -Ideps/pqm4/pqcrystals/kyber/ref
    -Ideps/pqm4/common
    -Ideps/pqm4/pqcrystals/kyber
    -DUSE_PQM4_KEM768
linker_script = ${platformio.build_dir}/ldscript.ld

[env:esp32c3]
build_src_filter = +<*> +<deps/pqm4/pqcrystals/kyber/ref/*.c> +<deps/pqm4/common/*.c>
platform = espressif32
lib_deps = 
    https://github.com/mupq/pqm4#main
    https://github.com/intel/tinycrypt#main
board = esp32c3-devkitm-1
framework = espidf
build_type = release
build_flags = 
    -std=c99
    -Os
    -ffunction-sections
    -fdata-sections
    -fno-builtin-malloc
    -fno-builtin-calloc
    -fno-builtin-realloc
    -fno-builtin-free
    -fno-exceptions
    -DCONFIG_FREERTOS_HZ=1000
    -Iinclude
    -Isrc
    -Isrc/core_rtos
    -Isrc/pqc_engine
    -Isrc/federated
    -Isrc/network
    -Ideps/pqm4/pqcrystals/kyber/ref
    -Ideps/pqm4/common
    -Ideps/pqm4/pqcrystals/kyber
    -DUSE_PQM4_KEM768

[env:native]
build_src_filter = +<*> +<deps/pqm4/pqcrystals/kyber/ref/*.c> +<deps/pqm4/common/*.c>
platform = native
build_type = debug
build_flags = 
    -std=c99
    -O0
    -g
    -fno-builtin-malloc
    -fno-builtin-calloc
    -fno-builtin-realloc
    -fno-builtin-free
    -Iinclude
    -Isrc
    -Isrc/core_rtos
    -Isrc/pqc_engine
    -Isrc/federated
    -Isrc/network
    -Ideps/pqm4/pqcrystals/kyber/ref
    -Ideps/pqm4/common
    -Ideps/pqm4/pqcrystals/kyber
    -DUSE_PQM4_KEM768

build_unflags = 
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17